### ISSUE TITLE
PlatformNotSupportedException (WebSocket)

### ISSUE THREAD

**Issue by wouayo** [JKorf/CryptoExchange.Net#106]
Hello,

I work on Win 7 - 64,
I have the "PlatformNotSupportedException" (from  websocket protocol) when using SubscribeToKlineUpdatesAsync() since i did an update of Binance.Net
... and i found this: "Removed Websocket4Net dependency in favor of a ClientWebSocket native implementation for websocket connections".

Does it mean the library will not longer works on win 7 ? There is a way to simply avoid this problem ?

Thanks.

**Comment by JKorf** [comment]
Hi, yes you're correct. Since websockets are not natively supported on Windows 7 it will no longer work on it. The older versions should still work, so you can continue to use that, but I would suggest updating to Windows 10 since Windows 7 is no longer supported by Microsoft and does not receive security updates anymore.

**Comment by wouayo** [comment]
Thanks for your answer.
Ok, i will downgrade for the moment.
I knew I was going to be in trouble sooner or later. It's the time. Damn, i was just getting used to Windows Seven :D

**Comment by AntiTenzor** [comment]
It looks like this library is a drop-in replacement for default implementation:
**https://   github.com   /PingmanTools/System.Net.WebSockets.Client.Managed/**

It would be VERY COOL if you will give an option to switch to this implementation.
