### ISSUE TITLE
Automatically sorted causes the signature to fail

### ISSUE THREAD

**Issue by wecando168** [JKorf/CryptoExchange.Net#156]
https://github.com/JKorf/CryptoExchange.Net/blob/0ddecf7f8dc84321dac801807f633ec6192a3ce5/CryptoExchange.Net/Clients/BaseRestClient.cs#L405
SendRequestAsync
ConstructRequest
PrepareRequestAsync

Can you provide a method that does not automatically sort the parameters, because using your code for secondary development, there is an exchange that submits parameters for signature data if it is automatically sorted, which will cause the signature to fail. The submission method he requires is: connection + parameters + timestamp + signature

**Comment by JKorf** [comment]
Hi, sorry for the delayed response. The sorting is intentional for the same reason you describe; some api's care about what sorting the parameters use. Have a look at the HuobiAuthenticationProvider to get an idea of auth is done there
https://github.com/JKorf/Huobi.Net/blob/master/Huobi.Net/HuobiAuthenticationProvider.cs

**Comment by alokym86** [comment]
@wecando168 try v5.3.1, now parameters are sorted before ConstructRequest() method, so the order should be the same.

**Comment by hyperms** [comment]
@JKorf Please disable auto-sort by default
Or at least put it as a method parameter
Or change the type of the output parameters to simple dictionary in AuthenticationProvider
