### ISSUE TITLE
CallResult Error code is null on request timed out

### ISSUE THREAD

**Issue by czernalex** [JKorf/CryptoExchange.Net#175]
**Describe the bug**
Recently some requests made with BinanceRestClient failed due to timed out. What actually surprised me was, that the Code in Error object was null and only Error message was filled with text: `[1] Request timed out`. I would like to add a custom rule to retry any request when this error happens next time, since it could be just some temporary problem with connection, however it would be much more convenient to handle this error based on Code property of Error object.

**To Reproduce**
When initializing RestClient in DI, try setting RequestTimeout option to extremely low value (like `TimeSpan.FromMiliseconds(1)`), then try sending any api request.

![image](https://github.com/JKorf/CryptoExchange.Net/assets/48368395/d02115a0-3d76-4c76-a51b-f5b591cfa2b7)

**Expected behavior**
I'm not really sure, but would probably expect the Code property of Error object not to be null.

Thank you for your help!

**Comment by JKorf** [comment]
The Code property is generally for some sort of status code. Could be the Http response status code or an error code from the server. Since we don't have either in this case it isn't filled.

You can however check the error type. If the error object is of the type WebError it means there was either a timeout or there was an error while trying to send the request. So you could do something like this:
```csharp
var result = await client.xx;
if (!result.Success)
{
  if (result.Error is WebError)
  {
    // Some retry logic
  }
}
```
