### ISSUE TITLE
KeepAlive in http requests

### ISSUE THREAD

**Issue by nikkozp** [JKorf/CryptoExchange.Net#43]
Hi @JKorf. Is set the KeepAlive connection in http requests?

[Example](https://stackoverflow.com/questions/36357943/c-sharp-how-to-set-httpclient-keep-alive-to-false)

**Comment by JKorf** [comment]
I've tried setting the Connection header to both Close and KeepAlive, but I've seen no timing difference between the two. If you can show me any data which suggests a performance improvement when setting the header I'll be happy to change it.

**Comment by ridicoulous** [comment]
@nikkozp
 I solved it via overriding [ConstructRequest method  ](https://github.com/ridicoulous/Bitmex.Net/blob/master/Bitmex.Net/BitmexClient.cs#L519 ) in my RestClient implementation. 

@JKorf requests with keep alive header should reuse existing connection, instead opening new (what can took at least 30-35ms). But according to [msdn](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.keepalive?view=netcore-3.1#remarks), keep alive connection is used by default if you uses HTTP 1.1
May be you didn't see any diffrenece, cause your server send Close header in responses?

**Comment by JKorf** [comment]
As you've pointed out @ridicoulous, because HTTP 1.1 is used the default is keep-alive anyway. With your PR changes of reusing the HttpClient it should now also be able to actually re-use the connection when making a second request. 

As far is I could see there is no notable performance difference (tested some requests to Binance). The consumed time per request is mainly waiting for the server to serve up the data, not making the connection.
