### ISSUE TITLE
Connection lost & time-limited subscription

### ISSUE THREAD

**Issue by MartyIX** [JKorf/CryptoExchange.Net#60]
Hi,

I'm curious about this line:

https://github.com/JKorf/CryptoExchange.Net/blob/133279b28bbeb50ad8d716e3c54773d2617de24f/CryptoExchange.Net/Sockets/SocketConnection.cs#L369

What would happen when one of those subscriptions is Binance User Data Stream? I'm asking because for that subscription you have to first obtain a listen key (string) via REST request and the listen key is valid only 60 minutes. I guess that if connection is lost at minute 61, then re-subscription must fail and it can never succeed, right? Will current implementation lead to infinite re-connecting or am I missing something?

**Comment by JKorf** [comment]
Not quite. The Binance websocket doesn't use subscribing. It just connects to an endpoint, and receives data based on what that endpoint is. When a connection is made to an endpoint (say listenkey) which doesn't exist or is expired, the connection attempt will still succeed, it just won't receive any data. 

So in the case of a longer network outage, the socket will reconnect just fine, it just won't receive any updates. 
You probably can't call a KeepAlive on an expired listenkey, so you'd still need to implement something to restart the stream with a new listenkey when the key is expired.

**Comment by MartyIX** [comment]
> Not quite. The Binance websocket doesn't use subscribing.

Ah, now I understand your definition of "subscribing".

> So in the case of a longer network outage, the socket will reconnect just fine, it just won't receive any updates.

Actually, my analysis tells me that that Binance User Data Stream is not re-subscribed because 

https://github.com/JKorf/Binance.Net/blob/5231d56006c1c26a107cbf9f3f6bf5302cb476a0/Binance.Net/BinanceSocketClient.cs#L101

where `request = null` 

and this leads to 

https://github.com/JKorf/CryptoExchange.Net/blob/a94e261bf164fcbf9be4055a2454bd8c1e79f257/CryptoExchange.Net/Sockets/SocketConnection.cs#L352

where handlers without `request`s are ignored.

So in the end, it behaves as I need. It's a little bit confusing for me as I don't understand what `request`:

https://github.com/JKorf/CryptoExchange.Net/blob/a94e261bf164fcbf9be4055a2454bd8c1e79f257/CryptoExchange.Net/Sockets/SocketSubscription.cs#L24

is abstraction for.

**Comment by JKorf** [comment]
Request is the request object which is sent to the server when it wants to subscribe. Typically it is a model which looks something like this (just an example):
````C#
public class SubscribeRequest
{
   public string Method { get; set; } = "Subscribe";
   public string Channel { get; set; }
}
````

This request object is saved for a handler. In case a reconnect happens the socket needs to resubscribe. It then takes all handlers which have such a subscribe request object and resends that same object to resubscribe to the correct channels.

In case of Binance this isn't needed because it automatically starts sending data based on what endpoint you connected to. So for Binance the request objects are null because they don't exist, and in case of reconnect there is no need to send anything.
